### ISSUE TITLE
Download all apk files of an app which was 'Varies with device'

### ISSUE THREAD

**Issue by portablesoft** [NeroBurner/googleplay-api#3]
For example:

https://play.google.com/store/apps/details?id=com.android.chrome

Size: Varies with device
Current Version: Varies with device
Requires Android: Varies with device

Is it possible to choose cpu architecture or ABIs and download all the apks? Thanks.

ABI Management
https://developer.android.com/ndk/guides/abis.html

**Comment by NeroBurner** [comment]
I think the abi and device are managed here https://github.com/NeroBurner/googleplay-api/blob/master/googleplay_api/googleplay.py#L197

you may change it or make it configurable

PR welcome ;)

**Comment by NeroBurner** [comment]
closed due to inactivity and because I don't use this repo anymore
